yaegassy/coc-volar

src/features/documentVersion.ts
src/index.ts

By porting `features/documentVersion.ts`, "diasnostics" now works properly.

feat: to port "documentVersion.ts" (diasgnotics ok)

---

README.md
package.json
src/const.ts
src/features/activeSelection.ts
src/features/attrNameCase.ts
src/features/documentContent.ts
src/features/documentVersion.ts
src/features/tagNameCase.ts
src/features/tsVersion.ts
src/index.ts
yarn.lock

@johnsoncodehk Very much refactoring, thanks!
Close  https://github.com/yaegassy/coc-volar-experimental/issues/2

feat: Remove VSCode dependency

---

package.json
src/index.ts

Close https://github.com/yaegassy/coc-volar/issues/8

feat: Add "volar.formatting.enable" option

---

src/index.ts

Added coc-volar's own logging for client. 
Add a resolved log for tsPaths in the workspace.
> [settings] "volar.useWorkspaceTsdk": true
**Capture**:

feat: Add client logging (volar-client)

---

README.md
src/action.ts
src/index.ts

feat: Add "@ts-ignore" code action 

---

package.json
src/features/tsVersion.ts
src/index.ts

Add locale settings of diagnostics messages from typescript.
https://user-images.githubusercontent.com/188642/129144560-91702043-e3b5-4bbb-b44b-1a86ad3c7633.mp4

feat: Add "volar.diagnostics.tsLocale" option

---

package.json
src/features/tagClosing.ts
src/index.ts

**coc-settings.json**:
> volar.autoClosingTags: true (default false)
- [coc-html](https://github.com/neoclide/coc-html)
- [coc-svelte](https://github.com/coc-extensions/coc-svelte)

feat: Add "volar.autoClosingTags" option

---

esbuild.js
package.json
src/features/splitEditors.ts

Refactored splitEditors by adding `@vue/compiler-sfc` and `@vue/reactivity` as dependencies.
https://user-images.githubusercontent.com/188642/129836632-c964c3ba-0c61-44ba-af13-6b08e7306540.mp4

refactor: "volar.action.splitEditors" commands (also add deps)

---

README.md

Change to demo using `<script setup>`.

chore: Update demo capture in README

---

README.md
package.json
src/index.ts
yarn.lock

- fix: attr name case option "pascalCase" -> "camelCase"

refactor: sync to volar v0.27.4

---

README.md
package.json
src/features/vueTscVersion.ts
src/index.ts
yarn.lock

feat: sync to volar v0.27.7
- Update to volar v0.27.7
- Add "volar.checkVueTscVersion" option (default "false")
- In coc-volar, set the default value to `false`
https://user-images.githubusercontent.com/188642/130360654-82b18eea-9e37-4b8d-85f4-effb5deac2ef.mp4
https://user-images.githubusercontent.com/188642/130360668-1a4b8c46-f660-4d19-9e6c-ba06a4059ac2.mp4

feat: sync to volar v0.27.7

---

README.md
package.json
src/index.ts

Helpful when dealing with issues.
https://user-images.githubusercontent.com/188642/130547612-fb6715ed-7ef2-4d7c-a518-2bcd05f4b364.mp4

feat: Add "volar.version" command (client/server version)

---

README.md
package.json
src/index.ts

- Add "volar.lowPowerMode" option
- [Not ported] Prompt-related features such as `registarLowPowerModeChange()` are **not** ported.
- change settings -> reload window
- disable -> open settings
https://user-images.githubusercontent.com/188642/131257365-8048d175-44df-4db4-bf1e-4c5da1da78f9.mp4

feat: low power mode

---

package.json
yarn.lock

Close https://github.com/yaegassy/coc-volar/issues/43
fixed the version to v4.3 for now.

fix(deps): bump typescript to ~4.3.5 (fix completion)

---

src/client/commands.ts

https://user-images.githubusercontent.com/188642/132426059-bd32b5f1-bb33-4f6e-9e35-2692c84255ba.mp4

feat: Add volar's settings to the doctor command

---

src/client/commands.ts

refactor(command): add vueTscVersion to "volar.doctor"

---

package.json
yarn.lock

- fix vueTscVersion later...
- In `coc-volar`, can't get it in `require.resolve`

chore: Sync volar v0.27.20 (fix vueTscVersion later...)

---

src/index.ts

**REF**:
- <https://github.com/johnsoncodehk/volar/issues/523>
- <https://github.com/johnsoncodehk/volar/commit/0073922c9cc9d622b5a76783fa5d442347d7fb03>

perf: add synchronize's watch file in clientOptions

---

README.md
package.json
src/index.ts

Added an option to change the memory allocation.
**Use case**:
- Increase memory allocation if memory is available
- Reduce the memory allocation if there is not enough memory
**Reference**:
- [yaegassy/coc-intelephense](https://github.com/yaegassy/coc-intelephense)
- [bmewburn/vscode-intelephense](https://github.com/bmewburn/vscode-intelephense)
https://user-images.githubusercontent.com/188642/136160806-ae5500e0-51c4-4b68-9e04-067046950a99.mp4

feat: add "volar.maxMemory" option

---

package.json
yarn.lock

**TODO**: 
- Code refactoring due to change of upstream entry point to nodeClientMain to be addressed in another PR

chore: update to volar v0.29.4 (I'll refactor later)

---

package.json
schemas/vue-tsconfig.schema.json

> coc-json needs to be installed
https://user-images.githubusercontent.com/188642/149703364-1d411cfb-0888-4fdf-be1a-13329c3a7f5b.mp4

feat: add vueCompilerOptions json schema

---

README.md
package.json
src/client/commands.ts

feat: add typescript, javascript and related to jsx to activationEvents

---

README.md
package.json
src/common.ts

Close https://github.com/yaegassy/coc-volar/issues/113

feat: add ts, js, tsx, jsx to activation events

---

README.md
package.json
src/common.ts
src/index.ts

- See Upstream: <https://github.com/johnsoncodehk/volar/commit/fc7a02c3a141f937d012ff862309bac2a9c34fb1>

refactor: langId related and mode changes & useSecondServer support

---

package.json
src/common.ts
src/features/inlayHints.ts

**coc-settings.json**:
```jsonc
{
// ...snip
"typescript.inlayHints.enumMemberValues.enabled": true,
"typescript.inlayHints.functionLikeReturnTypes.enabled": true,
"typescript.inlayHints.propertyDeclarationTypes.enabled": true,
"typescript.inlayHints.parameterTypes.enabled": true,
"typescript.inlayHints.variableTypes.enabled": true,
// ...snip
}
```
https://user-images.githubusercontent.com/188642/164455978-d9390526-cfe2-4c30-aa96-27e836552ea0.mp4

feat: inlay hints support

---

src/client/statusBar.ts
src/common.ts

https://user-images.githubusercontent.com/188642/169447322-ee71596c-fc1a-46bb-8b19-802b74f4326a.mp4

feat: add text to status-bar when Take Over Mode is enabled

---

README.md
package.json
src/common.ts
src/features/fileReferences.ts
src/requestTypes.ts

https://user-images.githubusercontent.com/188642/172511024-f6a64ef9-c51d-403b-a3fe-0fb8c8cbeb02.mp4

feat: add "vue.findAllFileReferences" command

---

src/index.ts

The vue file is fine, but I have confirmed that the problem is not resolved in the ts file and other files, so I will revert.

Revert "refactor(middleware): remove only processing related to document version in codeaction"

---

README.md
package.json
schemas/vue-tsconfig.schema.json
src/common.ts
src/features/reloadProject.ts
src/features/showReferences.ts
src/features/tsVersion.ts
src/features/verifyAll.ts
src/features/virtualFiles.ts
src/index.ts
src/requestTypes.ts
yarn.lock

Upstream is currently in ~alpha~ ~beta~ **rc** version, so this PR will not be merged yet.

Sync volar v1.0.0

---

src/common.ts
src/index.ts

REF: https://github.com/yaegassy/coc-volar/pull/219

refactor: use client.registerFeature

---

README.md
package.json
schemas/vue-tsconfig.schema.json
src/common.ts
src/features/serverStatus.ts
src/index.ts
src/requestTypes.ts
yarn.lock

- `watchman` may no longer be needed with coc-volar since volar `v1.0.9`.

Sync volar v1.0.9

---

package.json
src/common.ts
src/index.ts
yarn.lock

At this time, upstream is in alpha version, but also includes fixes for the following issues.
close, https://github.com/yaegassy/coc-volar/issues/254
There is also some refactoring.

Sync volar v1.2.2-alpha.2

---

README.md
package.json
src/common.ts
src/config.ts
src/features/autoInsertion.ts
src/index.ts
yarn.lock

This update includes significant changes to the configuration names and default values for various settings.
(Refer to the upstream): <https://github.com/vuejs/language-tools/pull/2620>

Sync volar v1.3.18

---

package.json
yarn.lock

- <https://github.com/vuejs/language-tools/pull/3215>

Sync volar v1.7.8

---

README.md
package.json
src/config.ts

Close https://github.com/yaegassy/coc-volar/issues/319

feat: add volar.disableCompletion setting

---

package.json

Close https://github.com/yaegassy/coc-volar/issues/345

fix: typescriptServerPlugins setting
