yaegassy/coc-volar

- src/features/attrNameCase.ts
- src/features/tagNameCase.ts
- src/index.ts
"HTML tags", "component names", and "directives" can now be complettion in the `<template>`.
I've ported the **minimum feature** for each auto completion to work.
> feat: HTML tag, component and directive completion in template

- src/features/tsVersion.ts
Failed to detect tsLibs in the workspace.
**Setting (coc-settings.json)**:
```jsonc
{
// ...snip
"volar.useWorkspaceTsdk": true,
// ...snip
}
```
Apply coc's fixes.
> Logging on ("volar-api.trace.server": "verbose")
> Logging on ("volar-api.trace.server": "verbose")
> fix: Detecting workspace ts path

- package.json
- src/index.ts
Like vetur's `vetur.dev.vlsPath`.
**e.g. settings**:
```jsonc
{
// ...snip
// Absolute path
"volar.dev.serverPath": "/Users/yaegassy/.local/src/volar/packages/server/out/index.js",
// ...snip
}
```
> feat: Add "volar.dev.serverPath" option

- package.json
- src/features/refComplete.ts
- src/index.ts
"autoCompleteRefs" has been implemented in the `refComplete.ts` file. (port, `tagClosing.ts`)
> **coc-settings.json**:
> volar.autoCompleteRefs: true (default false)
In coc-volar, `volar.autoCompleteRefs` is set to `false` by default.
> feat: Add "volar.autoCompleteRefs" option

- README.md
- package.json
- src/features/splitEditors.ts
- src/index.ts
Implemented using Vim's `split`, `vsplit` (vertical split), and `fold` related features.
> feat: Add "volar.action.splitEditors" commands

- package.json
- yarn.lock
Used `vscode-languageserver-protocol` in "tagClosing".
Currently installed as a dependency of `@volar/server` etc., but we have explicitly added it to deps
> chore(deps): Add vscode-languageclient

- package.json
Add the `vetur.enable` setting in "coc-volar" until this PR is merged. https://github.com/neoclide/coc-vetur/pull/76
> chore: Add "vetur.enable" option (for coc-vetur)

- README.md
- package.json
- src/index.ts
Volar's linting (diagsnotics) is a "core feature", it would be a very, very shame to disable it.
However, some users want to use only eslint (+eslint-plugin-vue).
Add a configuration option to enable/disable diagnostics. (Of course, default is `true`)
> feat: Add "volar.diagnostics.enable" option (Of course, default is true)

- README.md
- package.json
- src/client/commands.ts
- src/index.ts
Created a command to output various version information that may be relevant to `volar`.
https://user-images.githubusercontent.com/188642/132377473-bf668a3d-2dae-490e-b4df-c15e9067f783.mp4
> feat: Add "volar.doctor" command (show infomation)

- src/client/commands.ts
- src/features/vueTscVersion.ts
I don't use `pnpm`, but in the case of `pnpm`, I had to make adjustments to get the version of the dependent package
I checked with vue-tsc's `v0.3.0` and `v0.2.2` (deps: `vscode-vue-languageservice@0.26.16`).
> feat: support for package version detection when using "pnpm"

- src/common.ts
- src/index.ts
VSCode's volar extension has split the entry point into two in preparation for `github.dev` support. `nodeClientMain.ts` and `browserClientMain.ts`.
The entry point that "coc-volar" should focus on is `nodeClientMain.ts`. https://github.com/johnsoncodehk/volar/blob/master/extensions/vscode-vue-language-features/package.json#L34
> refactor: adjustments due to upstream's entry point changes

- README.md
- package.json
- src/client/commands.ts
Reverts yaegassy/coc-volar#114
---
Confirmed that the volar server is starting up even though the project is not Vue. For example, autocompletion is duplicated.
Reverts...
> Revert "feat: add typescript, javascript and related to jsx to activationEvents"

- README.md
- package.json
- src/client/commands.ts
- src/common.ts
This command disables the built-in formatter provided by volar's language server, and enables "prettier".
Used to quickly enable pretteir in a new Vue project created with `create-vue`, etc.
To use prettier, you need `coc-prettier`. As an additional note, vue files are disabled by default in coc-prettier.
https://user-images.githubusercontent.com/188642/153787961-2224901f-85a2-41ba-b403-2bf482f8fe82.mp4
> feat(command): add "volar.usePrettier" command

- README.md
- package.json
- snippets/vue.code-snippets
- src/client/completions.ts
- src/common.ts
Enable vetur's like scaffold snippets. Try typing `vue` or ` vuedc`.
**Add configuration option**:
- `volar.scaffoldSnippets.enable`: Enable/disable scaffold snippets completion. Typing `vue` or `vuedc` will output completion suggestions. This snippets completion feature will only work on the first line of the file, default: `true`
https://user-images.githubusercontent.com/188642/154611535-3d4a4102-2788-4c5f-9dca-256e2046aa64.mp4
If you need other snippets, try using [coc-snippets](https://github.com/neoclide/coc-snippets) or similar vim plugin.
> feat(completion): add "volar.scaffoldSnippets.enable" option

- README.md
- package.json
- src/client/commands.ts
- src/common.ts
The default value of `prettier.disableLanguages` has been changed in `coc-prettier` since "v9.2.0". Previously, `vue` was set to disable by default.
- **REF**:
- <https://github.com/neoclide/coc-prettier/issues/145>
- <https://github.com/neoclide/coc-prettier/blob/master/package.json#L42>
Because of this, if coc-prettier is installed, the built-in formatter of the Language Server (e.g. volar) will not be used, and prettier will be used preferentially.
For this reason, the `volar.usePrettier` command is unnecessary and has been removed.
Added explanation to README.
> refactor: remove "volar.usePrettier" command and docs adjustment

- package.json
- src/client/commands.ts
- src/features/tsVersion.ts
- src/index.ts
- yarn.lock
- ported the function of `shared.getWorkspaceTypescriptPath`
- Error when using `shared.getWorkspaceTypescriptPath` of `@volar/shared` v0.32.0 in `coc-volar`.
> refactor: sync volar v0.32.0

- package.json
- schemas/vue-tsconfig.schema.json
- src/common.ts
- src/index.ts
- yarn.lock
At this time, coc-volar does not support inlay hints. Also, there is currently no LSP client plugin for Vim8/Neovim that supports inlay hints by default, as far as I know.
In "Neovim", when representing inlay hints, there is a way to display virtual text at the end of a line.  Not supported in "Vim8"
This is an example for `coc-sumneko-lua` (use sumneko/lua-language-server).
Reference implementations exists `coc-rust-analyzer`, `coc-sumneko-lua` and `coc-tsserver` (server side).
- <https://github.com/fannheyward/coc-rust-analyzer/blob/master/src/inlay_hints.ts>
- <https://github.com/xiyaowong/coc-sumneko-lua/blob/main/src/inlay_hints.ts>
- <https://github.com/neoclide/coc-tsserver/blob/master/src/server/features/inlayHints.ts>
> Sync volar v0.34.8

- README.md
- package.json
- src/features/inlayHints.ts
"Toggle inlay hints" seem to have been added in VSCode 1.67. <https://code.visualstudio.com/updates/v1_67#_toggle-inlay-hints>
In the future, standard settings or commands, etc. may be added in coc.nvim, but we have added a dedicated toggle command in `coc-volar`.
Add toggle command for inlay hints like VSCode's `rust-analyzer` extension and `coc-rust-analyzer`.
- <https://github.com/rust-lang/rust-analyzer/tree/master/editors/code>
- <https://github.com/fannheyward/coc-rust-analyzer>
https://user-images.githubusercontent.com/188642/167049400-50be0a51-3326-48fd-839d-9f3fb19228de.mp4
> feat: add "volar.toggleInlayHints" command

- README.md
- package.json
- src/index.ts
`volar.vueserver.maxOldSpaceSize` was added in upstream. <https://github.com/johnsoncodehk/volar/pull/1299>
In coc-volar, a setting called `volar.maxMemory` was previously added for the same purpose. <https://github.com/yaegassy/coc-volar/pull/73>
Change from `volar.maxMemory` to `volar.vueserver.maxOldSpaceSize`.
> refactor: volar.maxMemory -> volar.vueserver.maxOldSpaceSize

- README.md
- package.json
- src/index.ts
There was a recent change in the notification-related features of `coc.nvim`. In `coc-volar`, a progress window is displayed when the language server is started.
https://user-images.githubusercontent.com/188642/172113068-b6a3ec2c-2993-47c3-9b2c-9e4cd3d65aa7.mp4
There seems to be a request to hide this progress window for coc.nvim itself and each coc.nvim extension.
Added a configuration at `coc-volar`.
> feat: "volar.progressOnInitialization.enable" configuration

- README.md
- package.json
- src/common.ts
- src/features/autoInsertion.ts
- src/index.ts
`coc-volar` provide a setting `volar.vitePressSupport.enable` (default: `false`).
If you want to use `.md` instead of `.vue` file in "VitePress", please enable this setting at the workspace (project) level.
**.vim/coc-settings.json**:
```jsonc
{
"volar.vitePressSupport.enable": true
}
```
> feat: VitePress support

- README.md
- package.json
- src/client/statusBar.ts
- src/common.ts
- src/index.ts
`coc-volar` provide a setting `volar.petiteVueSupport.enable` (default: `false`).
If you want to use .html instead of .vue extension in "petite-vue", please enable this setting at the workspace (project) level.
You must also place `tsconfig.json` or `jsconfig.json` in your project.
**.vim/coc-settings.json**:
```jsonc
{
"volar.petiteVueSupport.enable": true 
}
```
> feat: petite-vue support

- README.md
- package.json
Currently, volar's language server will not start properly if the `workspaceFolders` cannot be resolved properly.
**trace log**
```
[Warn  - 11:44:15 AM] No valid workspaceFolder exists
```
As a support, add a file to `rootPatterns` that can be recognized as a vue project by the extension.
- `vite.config.ts` (create-vue and create-vite)
- `vue.config.js` (vue-cli)
- `nuxt.config.ts` (nuxt3 and nuxt2)
Also, adjust the README for workspaceFolders-related.
> Add coc.nvim's own configuration, `contributes.rootPatterns`.

- package.json
- src/index.ts
Close #112 #134
I found a way to adjust Code Action on the client (coc-volar) side. Adjusted a problem that caused an error when executing Code Action and prevented it from being executed.
There are other issues related to code-action. volar's langauge sever also lists code-actions that are not executable in the current context.
I have tried to prevent non-executable actions from appearing in the list.
https://user-images.githubusercontent.com/188642/174920783-5ce862fe-b102-4950-a285-0080344c44d9.mp4
> refactor: add middleware for adjusting code-action

- src/index.ts
There was a commit to correct the problem on the language server side.
- https://github.com/johnsoncodehk/volar/commit/6791d8b786fb3941b803b69b5d76c63ada5f6ca3
Only middleware processes related to the document version were removed
- <https://github.com/yaegassy/coc-volar/issues/112>
- <https://github.com/yaegassy/coc-volar/issues/134>
- <https://github.com/johnsoncodehk/volar/issues/1490>
> refactor(middleware): remove only processing related to document version in codeaction

- package.json
- src/features/inlayHints.ts
- yarn.lock
The current coc-volar implementation of inlay hints uses a wrapper around the neovim api.
A feature for inlay hints was added in coc.nvim itself about 2 months ago.
- <https://github.com/neoclide/coc.nvim/commit/3a26df0abc7d432cca7a0ee6b8da3fc1ea5cae42>
I knew this feature had been added, but I had to wait for the passage of time to be able to use it unless I was using the relatively new coc.nvim.
As an additional note, on the `feat/3.17` branch of coc.nvim, if the Language Server supports inlay hints, inlay hints can be used without implementation on the extension side.
- <https://github.com/neoclide/coc.nvim/tree/feat/3.17>
- <https://github.com/neoclide/coc.nvim/commit/c69db06a4f1629ed7881f9a2d3be516d502fe699>
> refactor(inlay-hints): use languages.registerInlayHintsProvider

- src/common.ts
`__language` a hack add for VSCode and I wanted to remove it in VSCode by same way with this PR, I'm not sure `(params as any).locale` can pass to language server successfully, please let me know the this way not working.
> refactor: setting language via `InitializeParams.locale` instead of `__language`

- package.json
- src/index.ts
An update to coc.nvim itself caused a problem with `@` prefix completion.
- <https://github.com/yaegassy/coc-volar/issues/226>
- <https://github.com/neoclide/coc.nvim/issues/4348>
This problem has now been adjusted in coc.nvim itself, but it would be better to deal with the filtering of candidates on the extension side.
Add middleware to adjust completion feature.
> feat: add middleware for adjusting "@" prefix completion candidates

- package.json
It seems that there was a commit on the coc.nvim side that will adjust the problem of filtering completion candidates.
- <https://github.com/neoclide/coc.nvim/commit/7817ea6718d824b5715196982dda99265146c32a>
Change the setting to disable by default any middleware added on the extension side.
> chore: change volar.middleware.provideCompletionItem.enable default to false

- README.md
- package.json
- src/common.ts
Since the following diagnostics message is output when editing a jsonc format file (e.g. `tscofnig.json`, `coc-settings.json`, etc...), coc-volar removes the `volar.vueserver.json.customBlockSchemaUrls` setting itself.
For example, a error against commenting out.
**Diagnostics Message**:
```
[vue-semantic-server 521] Comments are not permitted in JSON. [E]
```
> Remove volar.vueserver.json.customBlockSchemaUrls setting

- README.md
- package.json
- src/client/commands/doctor.ts
- src/common.ts
- src/config.ts
- src/features/autoInsertion.ts
- src/index.ts
- yarn.lock
In this update, the names of the various settings have been significantly changed.
**Rename settings**:
- `volar.vueserver.configFilePath` -> `vue.server.configFilePath`
- `volar.vueserver.maxFileSize` -> `vue.server.maxFileSize`
- `volar.vueserver.petiteVue.processHtmlFile` -> `vue.server.petiteVue.supportHtmlFile`
- `volar.vueserver.vitePress.processMdFile` -> `vue.server.vitePress.supportMdFile`
- `volar.vueserver.diagnosticModel` -> `vue.server.diagnosticModel`
- `volar.vueserver.maxOldSpaceSize` -> `vue.server.maxOldSpaceSize`
- `volar.vueserver.reverseConfigFilePriority` -> `vue.server.reverseConfigFilePriority`
- `volar.vueserver.additionalExtensions` -> `vue.server.additionalExtensions`
- `volar.vueserver.fullCompletionList` -> `vue.server.fullCompletionList`
- …
> Sync volar v1.6.0

- src/features/autoInsertion.ts
Close https://github.com/yaegassy/coc-volar/issues/328
**Description**:
To enable this feature, you need to have a plugin installed that automatically inserts `}` when you type `{`, such as `jiangmiao/auto-pairs`. By the way, VS Code has this feature built-in by default.
**DEMO (mp4)**:
https://github.com/yaegassy/coc-volar/assets/188642/007d1fe0-0016-4a6c-b70f-f5efc68491b2
> feat: support `vue.autoInsert.bracketSpacing` feature

- package.json
- schemas/vue-tsconfig.schema.json
- yarn.lock
A mechanism to control `hybridMode` has been added, but `coc-volar` will update only the language server and TS plug-ins as they are now.
- REF
- <https://github.com/vuejs/language-tools/releases/tag/v2.0.7>
> Sync volar v2.0.7
